export const ALL_EMPLOYEES_REQUIREST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'


export const NEW_EMPLOYEES_REQUIREST = 'ALL_EMPLOYEES_REQUEST'
export const NEW_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const NEW_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'


export const CLEAR_ERRORS= 'CLEAR_ERRORS'